image: dockerhub.artifactory-phx.ecd.axway.int/library/docker:20.10.6

variables:
  PROJECT: "agents-apigee"
  CSR_SUPPRESSION_LIST: "/tmp/csr-suppressions/amplify-central/golang-agents-common.json"

  # # Fortify
  # FORTIFY_PROJECT: "10623"
  # FORTIFY_BUILD_ID: "azure_discovery_agent"

  # # Whitesource
  # WS_PROJECT_ID: "Azure-Discovery-Agent"
  WS_CONFIG_FILE: "whitesource.config"

  # just to be sure we don't do vendoring
  GOFLAGS: "-mod=mod"

stages:
  - test
  - sonar
  - build
  - security-scans
  - security-review

############################################################
# Section for included yaml files
############################################################
include:
  - project: "apigov/beano_cicd"
    ref: master
    # the order of these include files is important
    file:
      - "/gitlabci/variables.yml"
      - "/gitlabci/restrictions.yml"
      - "/gitlabci/jobs.yml"
  - project: "scurity/gitlabci"
    ref: master
    file:
      - "/.gitlab-ci-fortify.yml"
      - "/.gitlab-ci-whitesource.yml"
      - "/.gitlab-ci-iriusrisk.yml"
      - "/.gitlab-ci-twistlock.yml"
      - "/.gitlab-ci-csr.yml"
  - project: "apigov/beano_cicd"
    ref: master
    # this one MUST be after the scurity jobs in order for overrides to work correctly!
    file:
      - "/gitlabci/csrjobs.yml"

# twistlock-discovery:
#   extends: .twistlock
#   before_script:
#     - apk --no-cache update && apk add make
#     - make docker-build-discovery 
#     - export IMAGE_NAME=mulesoft_discovery_agent:latest
#   except:
#     refs:
#       - schedules
#       - tags
#       - main

# twistlock-traceability:
#   extends: .twistlock
#   before_script:
#     - apk --no-cache update && apk add make
#     - make docker-build-traceability 
#     - export IMAGE_NAME=mulesoft_traceability_agent:latest
#   except:
#     refs:
#       - schedules
#       - tags
#       - main

# twistlock-discovery:on-schedule:
#   extends: .twistlock
#   dependencies: []
#   before_script:
#     - apk --no-cache update && apk add git
#     - *get-latest-tag
#     - export IMAGE_NAME=ghcr.io/axway/mulesoft_discovery_agent:${GIT_TAG_PREFIX}${LATEST_TAG}
#     - docker pull ${IMAGE_NAME}
#   only:
#     refs:
#       - schedules

# twistlock-traceability:on-schedule:
#   extends: .twistlock
#   dependencies: []
#   before_script:
#     - apk --no-cache update && apk add git
#     - *get-latest-tag
#     - export IMAGE_NAME=ghcr.io/axway/mulesoft_traceability_agent:${GIT_TAG_PREFIX}${LATEST_TAG}
#     - docker pull ${IMAGE_NAME}
#   only:
#     refs:
#       - schedules

whitesource:on-schedule:
  extends: .whitesource
  before_script:
    - git config --global http.sslVerify false
    - git config --global url."ssh://git@git.ecd.axway.org".insteadOf "https://git.ecd.axway.org"''
    - git fetch
    - *get-latest-tag
    - echo "Checking out ${GIT_TAG_PREFIX}${LATEST_TAG}"
    - git checkout ${GIT_TAG_PREFIX}${LATEST_TAG}

# overridden from csrjobs.yml because mirror repos like this one don't get merge events
fetch-fortify:
  only:
    refs:
      - /^APIGOV-.*$/

run-csr:
  only:
    refs:
      - /^APIGOV-.*$/

whitesource:
  only:
    refs:
      - /^APIGOV-.*$/

####################
# CSR - overridden from csrjobs.yml to effectively not see these jobs ever. For some reason, probably multi-level
# extends and overrides, using only-never for these csr jobs doesn't work. Had to do it like this.
####################
fetch-iriusrisk:
  only:
    refs:
      - never
  except:
    refs:
      - neverever

fetch-iriusrisk:on-schedule:
  only:
    refs:
      - never
  except:
    refs:
      - neverever

twistlock:
  only:
    refs:
      - never
  except:
    refs:
      - neverever
  dependencies:

twistlock:on-schedule:
  only:
    refs:
      - never
  except:
    refs:
      - neverever

twistlock-master:
  only:
    refs:
      - never
  except:
    refs:
      - neverever

###################
# These overridden from jobs.xml to never run      
###################
test:
  extends: .only-never
