image: dockerhub.artifactory-phx.ecd.axway.int/library/docker:20.10.6

variables:
  PROJECT: "agents-apigee"
  CSR_SUPPRESSION_LIST: "/tmp/csr-suppressions/amplify-central/golang-agents-common.json"

  # # Fortify
  # FORTIFY_PROJECT: "10623"
  # FORTIFY_BUILD_ID: "azure_discovery_agent"

  # # Whitesource
  # WS_PROJECT_ID: "Azure-Discovery-Agent"
  WS_CONFIG_FILE: "whitesource.config"

  GIT_TAG_PREFIX: v

  # just to be sure we don't do vendoring
  GOFLAGS: "-mod=mod"

stages:
  - test
  - sonar
  - build
  - security-scans
  - security-review

############################################################
# Section for included yaml files
############################################################
include:
  - project: "apigov/beano_cicd"
    ref: master
    # the order of these include files is important
    file:
      - "/gitlabci/variables.yml"
      - "/gitlabci/restrictions.yml"
      - "/gitlabci/jobs.yml"
  - project: "scurity/gitlabci"
    ref: master
    file:
      - "/.gitlab-ci-fortify.yml"
      - "/.gitlab-ci-whitesource.yml"
      - "/.gitlab-ci-twistlock.yml"
      - "/.gitlab-ci-csr.yml"
  - project: "apigov/beano_cicd"
    ref: master
    # this one MUST be after the scurity jobs in order for overrides to work correctly!
    file:
      - "/gitlabci/csrjobs.yml"

####################
# CSR - overridden from csrjobs.yml to effectively not see these jobs ever. For some reason, probably multi-level
# extends and overrides, using only-never for these csr jobs doesn't work. Had to do it like this.
####################
fetch-iriusrisk:
  only:
    refs:
      - never
  except:
    refs:
      - neverever

fetch-iriusrisk:on-schedule:
  only:
    refs:
      - never
  except:
    refs:
      - neverever

fetch-iriusrisk:on-schedule:
  only:
    refs:
      - never
  except:
    refs:
      - neverever

twistlock:
  only:
    refs:
      - never
  except:
    refs:
      - neverever
  dependencies:

twistlock:on-schedule:
  only:
    refs:
      - never
  except:
    refs:
      - neverever

twistlock-master:
  only:
    refs:
      - never
  except:
    refs:
      - neverever
