name: Discovery Agent Docker

on:
  push:
    tags:
      - "*"

jobs:
  buildDiscoveryAgentDocker:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
      IMAGE_NAME: webmethods_discovery_agent
      ORG_NAME: Axway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create commit_id & version environment variables
        run: |
          commitId=$(git rev-parse --short HEAD)
          echo "commitId=$commitId" >> $GITHUB_ENV
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          images: ghcr.io/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/discovery.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
              VERSION=${{ github.ref_name }}
              COMMIT_ID=${{ env.commitId }}

  buildTraceabilityAgentDocker:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
      IMAGE_NAME: webmethods_traceability_agent
      ORG_NAME: Axway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create commit_id & version environment variables
        run: |
          commitId=$(git rev-parse --short HEAD)
          echo "commitId=$commitId" >> $GITHUB_ENV
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          images: ghcr.io/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/traceability.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: | 
              VERSION=${{ github.ref_name }}
              COMMIT_ID=${{ env.commitId }}

  notifyTeamsChannel:
    runs-on: ubuntu-latest
    needs: [buildDiscoveryAgentDocker, buildTraceabilityAgentDocker]
    steps:
      - name: Notify Teams channel
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          TAG: ${{ github.ref_name }}
        run: ./release.sh
            