# this action will upload the assets (name: Upload assets to release

on:
  push:
    tags:
      - "xxxx"

jobs:
  buildDiscoveryAgent:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build discovery agent
        working-directory: .
        run: |
          git rev-parse --short HEAD > commit_id
          echo "${{ github.ref_name }}" > version
          make build-discovery

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/discovery
          asset_name: webmethods_discovery_agent
          tag: ${{ github.ref }}
          overwrite: true
          body: "webMethods Discovery Agent - ${{ github.ref }}"

  buildTraceabilityAgent:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build traceability agent
        working-directory: .
        run: |
          git rev-parse --short HEAD > commit_id
          echo "${{ github.ref_name }}" > version
          make build-trace
          ls -laR

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/traceability
          asset_name: webmethods_traceability_agent
          tag: ${{ github.ref }}
          overwrite: true
          body: "webMethods Traceability Agent - ${{ github.ref }}"

      - name: Upload release yaml
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/webmethods_traceability_agent.yml
          asset_name: webmethods_traceability_agent.yml
          tag: ${{ github.ref }}
          overwrite: true
          body: "webMethods Traceability Agent YAML - ${{ github.ref }}"

  notifyTeamsChannel:
    needs: [buildDiscoveryAgent, buildTraceabilityAgent]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Notify Teams channel
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          TAG: ${{ github.ref_name }}
        run: ./release.sh
